services:
  db:
    image: postgres:16-alpine
    container_name: devboard_db
    environment:
      POSTGRES_USER: ilyassoudli
      POSTGRES_PASSWORD: ilyass
      POSTGRES_DB: devboard
    ports:
      - "5433:5432"
    volumes:
      - devboard_db_data:/var/lib/postgresql/data
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

  backend:
    build: ./backend
    container_name: devboard_backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env.docker
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend/devboard
      dockerfile: ../Dockerfile
    container_name: devboard_frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://backend:4000
    depends_on:
      - backend

volumes:
  devboard_db_data: